name: Build and deploy container app to Azure Web App - daelim-RAG-chatbot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Azure Container Registry (ACR)
      uses: docker/login-action@v2
      with:
        registry: daelimregistry.azurecr.io
        username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: daelimregistry.azurecr.io/daelim-rag-chatbot:latest

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: daelim-RAG-chatbot
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: daelimregistry.azurecr.io/daelim-rag-chatbot:latest
